version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: bitriseio/docker-android:latest
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-25;google_apis;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"
      - run:
          name: Launch emulator
          command: /opt/android-sdk-linux/emulator/emulator -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait for emulator
          command: ./android-wait-for-boot.sh

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - run:
          name: Run Instrumentation Tests
          command: ./gradlew :app:connectedAndroidTest

      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results